name: Corep
favicon: null
layout_spectrum: 0.75361
typography_spectrum: 0.24819
title: Lighting Mnaufacturer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D0C8A8'
    - '#484020'
    - '#685838'
    - '#C0A878'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
