name: Corep
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.3565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#311309'
    - '#764328'
    - '#fefefe'
    - '#b68879'
    - '#cec3c1'
  brandStrength: 0.8236768145579845
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
