name: Corep
favicon: null
layout_spectrum: 0.99549
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d7d3d0'
    - '#9d9690'
    - '#e2e1dd'
    - '#aeaba4'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
