name: Corep
favicon: null
layout_spectrum: 0.2601331206969917
typography_spectrum: 0.6373899367172271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8236768145579845
  lightness: 0.08926635258831084
  saturation: 0.3492065751925111
  rhythmicContrast: 0.9087610139977187
purpose: []
