name: Corep
favicon: null
layout_spectrum: 0.2601331206969917
typography_spectrum: 0.3565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3c3c1'
    - '#e2d8d0'
    - '#a9947e'
    - '#bfa28b'
    - '#847867'
  brandStrength: 0.8236768145579845
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
