analytics: {}
color:
  brandColors:
    - '#D0C8A8'
    - '#484020'
    - '#685838'
    - '#C0A878'
    - '#000000'
  brandStrength: 0.666666
  lightness: 0.03125
  rhythmicContrast: 0.6875
  saturation: 0.505208
cta: {}
layout_spectrum: 0.596354
name: Corep
opengraph: {}
purpose: []
typography_spectrum: 0
