name: Corep
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Corep - The Lighting Tailors
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d7d3d0'
    - '#9d9690'
    - '#e2e1dd'
    - '#aeaba4'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
